### ISSUE TITLE
Update actions

### ISSUE THREAD

**Issue by Career200** [sitek94/vite-deploy-demo#2]
![image](https://user-images.githubusercontent.com/105638831/219024892-7f09f6ef-1b55-46b1-a114-47373a65d50f.png)

It seems reasonable to update not only the actions, but set `node-version: latest` by default

```
      - name: Checkout repo
      # old - uses: actions/checkout@v2
        uses: actions/checkout@v3 

      - name: Setup Node
      # old - uses: actions/setup-node@v1
        uses: actions/setup-node@v3
        with:
      #old - node-version: 16
          node-version: latest

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
      # old: uses: actions/upload-artifact@v2
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
<...>
    steps:
      - name: Download artifact
      # old - actions/download-artifact@v2
        uses: actions/download-artifact@v3
<...>
```
